packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  hono: ^4.6.20
  tailwind-merge: ^2.5.4
  tailwindcss-animate: ^1.0.7
  tailwindcss: ^3.4.14
  eslint: ^9.20.0
  autoprefixer: ^10.4.20
  postcss: ^8.4.47
  prettier: ^3.4.2
  typescript: ^5.6.3
  "@types/node": ^20
  "zod": ^3.24.1

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.8
    "@types/react-dom": ^19.0.3
