packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  hono: ^4.6.20
  tailwindcss: ^4.0.4
  eslint: ^9.20.0
  prettier: ^3.4.2
  typescript: ^5.6.3
  "@types/node": ^20
  "zod": ^3.24.1
  "drizzle-orm": ^0.39.2

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^18.3.1
    "@types/react-dom": ^18.3.0
